### ISSUE TITLE
Game bug?

### ISSUE THREAD

**Issue by Gyrofalcon** [Rfvgyhn/gwent-tracker#10]
In your last release (1.4.0) I now see that "Francesca Findabair: the Beautiful" is listed with 2 copies. 
And I have only one, so that could explain why Base Game Card Progress is at 199/200

Is it possible to get 2 copies of that card in the game?
Thank you for a very helpful app :)

**Comment by rfvgyhn** [comment]
This is something I'm not positive about. In my save files that have the card, it lists it has having two. I've tried other peoples saves as well and theirs also have two copies. I assumed it was a bug with the game but if you only have one copy, I'm not sure. Which version of the game do you have (version number, steam/gog, dlc)?

**Comment by Gyrofalcon** [comment]
GoG platform, Game of the Year, v 1.32
http://gwent-cards.com/ are listing up 196 cards

**Comment by rfvgyhn** [comment]
Looks like my save game shows more duplicates besides the Francesca card. I have four _Pour Fucking Infantry_ (2/2, 1/1, 1/1) cards but that site lists three. I'll go through that list to find all the miscounts, double check them in game and add some special rules for them since it looks like the game doesn't report the correct number for some of them.

**Comment by Gyrofalcon** [comment]
Thank you. My deck also have the same collection of _Pour Fucking Infantry_ (2/2, 1/1, 1/1), and that is matching what's ingame. Hmmm
![2020-02-07_1717_1](https://user-images.githubusercontent.com/36332293/74045945-f40f7b00-49cd-11ea-8699-cfd037c4da0d.png)

**Comment by rfvgyhn** [comment]
Well, maybe in that case I should add some special logic just for the Francesca card. It only makes sense to have one of them since it's a leader card. You have the _Card Collector_ achievement with your 199 cards right?

**Comment by Gyrofalcon** [comment]
Yes, I indeed have the achievement.

**Comment by Gyrofalcon** [comment]
Another thing: With "Cow" the card "Bovine Defense Force" are summon. And it happens in my Gwent matches, so I "have" the card, even I never acquired it directly in the game. That card is not checked by the app as "found".  How to get around that challenge?

(Source https://witcher.fandom.com/wiki/Bovine_Defense_Force_Initiative)

**Comment by rfvgyhn** [comment]
Can you create a new issue for that so I can track it separately?
