### ISSUE TITLE
Scaling Problem

### ISSUE THREAD

**Issue by Lumbago1337** [Rfvgyhn/gwent-tracker#12]
I have set a higher DPI in Windows, which makes the program/tool also bigger. Then I'm unable to see the bottom of the left site with the information of the card. As a workaround I repositioned the monitors in Windows, but this is not really user-friendly. I think an easy way to resolve this is to add a scroll bar for the left site as well - or let me set a different size via config.

**Comment by rfvgyhn** [comment]
I added a scroll bar to the bottom-left section. Let me know if that wasn't what you meant.
