### ISSUE TITLE
Add Offline Card Pictures

### ISSUE THREAD

**Issue by Lumbago1337** [Rfvgyhn/gwent-tracker#13]
As a nice feature it would be cool to have all the cards as an offline version, so you don't have to make connection every time to the Windows servers, when you click a card. Also, when you block the internet connection of that program it will just crash.

**Comment by rfvgyhn** [comment]
This is now supported. If you'd like to pre-load all of the textures, [download them](https://www.nexusmods.com/witcher3/mods/4596/) and copy all of the numbered images into a folder named `textures`.

```
├── data
├── GwentTracker.exe
├── GwentTracker.exe.config
├── lib
├── locale
├── settings.ini
└── textures
    ├── 0.png
    ├── 10.png
    ├── 11.png
    ├── 7.png
    ├── 8.png
    └── 9.png
```
