### ISSUE TITLE
Data parsing 

### ISSUE THREAD

**Issue by VitalyVaryvdin** [Rfvgyhn/gwent-tracker#14]
Hi,
This issue isn't related to tool functioning directly, but i hope you'll be able to help me.

I'm working on some tool that needs data gathering on Gwent from W3. So far i have extracted and swapped channels on all Gwent card textures and extracted w3strings. I'm having hard time understanding how to connect variable from def_gwint_final_cards.xml to localized strings from w3strings. 

If you could share insights on how you achieved that or share source code for these tools that would be great.

**Comment by rfvgyhn** [comment]
To be honest, I don't remember how I came up with generating the correct values. I'm not sure if I figured it out or got it from someone else, but the localized strings ids are hashed versions of their keys in the xml files.

Using the following function with the card's title and description keys as its parameter would provide the hash found in w3strings. Looping through all of keys in the xml files is how I generated the [map file](https://github.com/Rfvgyhn/gwent-tracker/blob/master/tools/card-id-hash-map.txt).

```
private uint HashKey(string key)
{
    uint hash = 0;
    foreach (char c in key.ToCharArray())
    {
        hash *= 31;
        hash += (uint)c;
    }
    return hash;
}

Console.WriteLine(HashKey(Args[0]).ToString("x"));
```

For example, running via C# interactive, `csi hash-localization-key.csx gwint_desc_redanian` = `10884bc6`

There are a couple special cases:
* Avallach's card has a title of `Mysterious elf`. The localization key for it is actually `gwint_name_avallach`.
* Crach an Craite's card has a title of `Crach_an_Craite` but the hash is case sensitive. So it should be `crach_an_craite` which equals `f3a32552`

Let me know if you need more details.

**Comment by VitalyVaryvdin** [comment]
Thanks for the help, appreciate it a lot.
I'll get back to you once I settle with this. So far it looks like that was the only issue.

**Comment by VitalyVaryvdin** [comment]
Worked perfectly. Thanks for pointing out the inconsistency in titles.
However, another issue appeared - how did you get max copies number for each card? XML def files don't define that. Did you parse gwintManager.ws as well for that?

**Comment by rfvgyhn** [comment]
That came from parsing my save file where I had all of the cards and cross-checking that with various online guides about gwent cards.

**Comment by VitalyVaryvdin** [comment]
So that was manually put inside yml?

пн, 7 сент. 2020 г., 03:11 Chris <notifications@github.com>:

**Comment by rfvgyhn** [comment]
Correct.
