### ISSUE TITLE
No cards tracked on 4.1

### ISSUE THREAD

**Issue by majkrzak** [Rfvgyhn/gwent-tracker#16]
I've lunched the linux runtime version of the application and no gwent card is marked ass collected. The `defaultSavePath` points to the correct directory, log file claims no error.

**Comment by rfvgyhn** [comment]
Is this for a save game from the remastered version (v4.0 I think) of the game? It's possible the file format is different now.

**Comment by majkrzak** [comment]
Yes, sorry I forgot to mention. I'm on the latest steam version of the game 4.1 i think.

**Comment by rfvgyhn** [comment]
Fix for this will be included in the next release.
